name: Build Release Assets

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: create release
    runs-on: 'ubuntu-latest'
    steps:
      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  linux:
    name: build for Linux
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          npm install
      - name: build for Linux
        run: |
          npm run build -- --platform=linux
          cd dist
          tar zcvf electronic-plex-linux-x64.tar.gz electronic-plex-linux-x64
      - name: upload Linux release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/electronic-plex-linux-x64.tar.gz
          asset_name: electronic-plex-linux-x64.tar.gz
          asset_content_type: application/gzip

  windows:
    runs-on: 'windows-latest'
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          npm install
      - name: build for Windows
        run: |
          npm run build -- --platform=win32
          cd dist
          zip -r electronic-plex-win32-x64.zip electronic-plex-win32-x64
      - name: upload Windows release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/electronic-plex-win32-x64.zip
          asset_name: electronic-plex-win32-x64.zip
          asset_content_type: application/zip

  macos:
    runs-on: 'macos-latest'
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          npm install
      - name: build for macOS
        run: |
          npm run build -- --platform=darwin
          cd dist
          zip -r electronic-plex-darwin-x64.zip electronic-plex-darwin-x64
      - name: upload OSX release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/electronic-plex-darwin-x64.zip
          asset_name: electronic-plex-darwin-x64.zip
          asset_content_type: application/zip
