name: Lint Source Code

on: [push, pull_request]

jobs:
  linux:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          npm install
      - name: check formatting
        run: |
          npm run lint
